JuliaRobotics/Caesar.jl

examples/database/python/neo_interaction.py

A barebones example of interacting with Neo4j through Python, with comments. Saves some number of odometry variables, plus necessary factor var and some random number of landmark variables.

Python interaction

---

examples/rov/asfm/LRBEzpitch45deg.jl
examples/visualization/basicvisualizations.jl
src/Caesar.jl
src/ModelVisualizationUtils.jl
src/UserFunctions.jl
src/VisualizationUtils.jl

landmarks wont draw properly yet.

Tree type DrakeVisualizer interaction,

---

REQUIRE
examples/database/BuildCloudFactorGraph.jl
examples/database/CloneGraphBySess.jl
examples/database/MM-iSAMCloudSolve.jl
examples/database/RandomCloudGraphsInteraction.jl
examples/database/ReadAcousticTest.jl
examples/database/ReadNewData.jl
examples/database/convertslamindb.jl
examples/database/dbgFullLocalGraphCopy.jl
examples/database/plotpose2.jl
src/Caesar.jl
src/CloudGraphIntegration.jl
src/VisualizationUtils.jl

will initially fail, till RoME release is moved forward.

Nicksandsintg df

---

examples/database/python/neo_update.py

based on mongo oid value to be stored in existing node

to update a key in neo,

---

src/VisualizationUtils.jl

fix issue #61

---

examples/database/Slam2dExampleHexagonalCG.jl

@GearsAD please note that I am moving the Hexagonal example here from RoME.

moving example file from RoME to Caesar

---

README.md
REQUIRE

update require and readme

---

src/cloudgraphs/CloudGraphIntegration.jl
src/cloudgraphs/slamindb.jl

fixed MAP_est

---

docs/make.jl
docs/src/arena_visualizations.md
docs/src/database_interactions.md
docs/src/func_ref.md
docs/src/tut_hexagonal2d.md

improving 2D vis docs

---

docs/src/tut_hexagonal2d.md

more detail in docs

---

docs/src/arena_visualizations.md
docs/src/tut_hexagonal2d.md
docs/src/tut_slamedonut.md
examples/database/0_HexagonalSlam2d.jl
examples/database/dbg_packedtype_conversions.jl
examples/database/dev/BasicCloudGraphsSLAM.jl
src/cloudgraphs/CloudGraphIntegration.jl
src/cloudgraphs/ConvertGeneralSlaminDB.jl

xref: JuliaRobotics/RoME.jl#76

new PriorPoint2 PriorPose2 APIs

---

docs/make.jl

trying to get docs to deploy properly.

docs make update

---

src/zmq/models/distributions.jl

add Packed_BallTreeDensity

---

docs/src/concepts/adding_variables_factors.md
docs/src/concepts/building_graphs.md
docs/src/examples/basic_hexagonal2d.md
docs/src/examples/basic_slamedonut.md
docs/src/examples/interm_dynpose.md

Same for Pose or other factors
fix #143

Point2 replaces Point2D,

---

src/UserFunctions.jl

API update identitypose6fg!,

---

docs/src/concepts/concepts.md

add better variable factor definition

---

docs/src/func_ref.md

adding more functions to docs

---

examples/marine/rov/highend/synchronySDKIntegration.jl
src/cloudgraphs/CloudGraphIntegration.jl

adding local memory only feature,

---

docs/make.jl
docs/src/func_ref.md

update docs, fix #264

---

docs/src/examples/basic_slamedonut.md

update range only example

---

docs/src/func_ref.md

adding assignTreeHist function docs

---

examples/dev/BruteForceTreeOrderings.jl
examples/dev/QuestioningVariableOrder.jl
examples/marine/auv/Sandshark/dev/Funky21Problem.jl
examples/marine/auv/Sandshark/dev/Funky21Problem_Piecemeal.jl
examples/marine/auv/Sandshark/dev/FunkyContinuous.jl

some dev on variable order costs

---

examples/ros/RExRadarProcessor.jl

adding new radar file,

---

docs/src/examples/interm_dynpose.md

partly fixes JuliaRobotics/IncrementalInference.jl#580

DOCS drop softtype labels

---

examples/ros/RExFeed.jl
examples/ros/RExLidarProcessor.jl

This is an example on how to pull data from a ROS bag and into a DFG object (w/ datastore)

ROS example (via RobotOS.jl)

---

docs/src/installation_environment.md

AOT compile rome, initial

---

Project.toml
examples/wheeled/racecar/ros/CarSlamGenResults.jl
src/zmq/ZmqCaesar.jl
src/zmq/services/ZmqServer.jl
src/zmq/services/factors/factorSerialization.jl
src/zmq/services/plotting.jl

Requires RoMEPlotting, fix deps

---

src/images/images.jl

To work with multiple colors requires, although Caesar compat will not be adjusted accordingly 
- IIF v0.15.2
- FSM v0.2.3
See JuliaRobotics/IncrementalInference.jl#874

allow colors

---

docs/src/concepts/concepts.md
docs/src/concepts/multilang.md

Hi @pvazteixeira , thank for the updates.  I'm happy to merge these fixes unless you have objections?

doc updates

---

docs/src/refs/literature.md

micro Lie for state estimation in robotics

---

docs/src/refs/literature.md

Thanks to @kellertuer for point out the reference: https://github.com/JuliaManifolds/Manifolds.jl/pull/366#issuecomment-854978701

REF: Boumal, Intro to Optimization on Manifolds

---

Project.toml
examples/dev/apriltagserver/EasySLAMExAprilTags.jl
examples/dev/scalar/boxy.jl
examples/dev/scalar/demtest.jl
examples/dev/scalar/helix2D_ex5.jl
examples/marine/asv/rex/ScanMatcher.jl
examples/wheeled/racecar/testFluxModelsPose2.jl
src/images/Pose2AprilTag4Corners.jl
test/testPose2AprilTag4Corner.jl

needs IIF v0.24.4 and RoME v0.15.2

simplifying scalar box ex4 code towards generators

---

docs/src/examples/basic_definingfactors.md

HI Johan, thanks!  Going to merge this and keep updating with more PRs

WIP docs update for custom factors on manifold

---

examples/marine/asv/philos/IngestROSbag.jl
src/images/ScatterAlignPose2.jl
src/ros/Utils/RosbagSubscriber.jl

must standardize towards regular subscriber:
https://github.com/jdlangs/RobotOS.jl/blob/master/src/pubsub.jl

rosbag subscriber now always converts to msgtype

---

examples/calibration/dungbeetles/calibration_IPG.jl

@Affie @dehann merging this to the branch. Thanks @Affie for the neat solution!

Camera calibration example using IPG library

---

docs/src/examples/custom_variables.md

Linking to Manifolds! cc @mateuszbaran, @kellertuer

clean up custom variable docs,

---

examples/dev/devCSMHexDelayMatrix.jl
examples/dev/middleware/web/01_duplicate_hexagonal.jl
examples/dev/scalar/boxy.jl
examples/dev/scalar/ex5/demtest.jl
examples/dev/scalar/onedim.jl
examples/dev/scalar/onedim_sequence.jl
examples/dev/scalar/sampler-dev.jl
examples/dev/scalar/test-sequences-boxy2d.jl
examples/wheeled/racecar/apriltag_and_zed_slam_pynn.jl
test/beamforming/testExportImport.jl
test/beamforming/testFwdBackConv.jl
test/pcl/testPointCloud2.jl
test/testPose2AprilTag4Corner.jl

`pkgdir` is available since Julia 1.4 (https://github.com/JuliaLang/julia/blob/v1.4.0/NEWS.md) and this repo is lower bounded to Julia 1.4:
https://github.com/JuliaRobotics/Caesar.jl/blob/9c8e21d93d9cc2f9fbe74771652f159bfa313eb5/Project.toml#L78
```julia
julia> dirname(dirname(pathof(Revise))) == pkgdir(Revise)
true
```

Use `pkgdir` instead of `pathof`

---

docs/src/refs/literature.md

Not sure why Rutgers has the PDF up, but looks right.

Characterizing Marginalization ops Bayes Tree

---

Project.toml
test/ICRA2022_tests/simple_graph.jl
test/runtests.jl

end to end test for ICRA 2022 Tut1

---

test/ICRA2022_tests/nongaussian_mixture.jl
test/ICRA2022_tests/runtests.jl
test/runtests.jl

test ICRA Tut2,

---

src/images/ScatterAlignPose2.jl
src/plotting/ScatterAlignPlotting.jl
test/ICRA2022_tests/insufficient_data.jl
test/testScatterAlignPose2.jl

towards replacing 
- #611 
with `IIF.preambleCache` serialization strategy

ScatterAlignPose2 clouds in cache

---

test/ICRA2022_tests/insufficient_data.jl
test/ICRA2022_tests/multihypo_corners.jl
test/ICRA2022_tests/runtests.jl
test/testScatterAlignPose2.jl

closes:
- https://github.com/JuliaRobotics/Caesar.jl/issues/853
requires IIF v0.28.1

numerical test, ICRA Tut4

---

docs/src/concepts/solving_graphs.md

add docs for initVariable!

---

src/3rdParty/_PCL/services/ConsolidateRigidTransform.jl

suggestion from @Affie , thanks!

slightly faster mmatrix type

---

src/3rdParty/_PCL/services/PointCloudUtils.jl
src/objects/ObjectAffordanceSubcloud.jl

requries:
- JuliaRobotics/IncrementalInference.jl#1651

OAS as nary factor works

---

src/3rdParty/_PCL/services/LasIOSupport.jl

I haven't looked if any tests cover these functions yet.

Color LAS load and save

---

docs/src/concepts/arena_visualizations.md
test/pcl/testPointCloud2.jl

requires:
- JuliaRobotics/Arena.jl#119

docs Arena.jl plotPointClouds example
